config/routes.rb
Activize::Application.routes.draw do
  devise_for :users
  resources :petitions

  root 'petitions#index'

end

app/models/petition.rb
class Petition < ActiveRecord::Base
	belongs_to :user
#	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :petitions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_petition, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]




  # GET /petitions
  # GET /petitions.json
  def index
    @petitions = Petition.order("id DESC").all
  end

  # GET /petitions/1
  # GET /petitions/1.json
  def show
  end

  # GET /petitions/new
  def new
    @petition = current_user.petitions.build
  end

  # GET /petitions/1/edit
  def edit
  end

  # POST /petitions
  # POST /petitions.json
  def create
    @petition = current_user.petitions.build(petition_params)

    respond_to do |format|
      if @petition.save
        format.html { redirect_to @petition, notice: 'Petition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @petition }
      else
        format.html { render action: 'new' }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /petitions/1
  # PATCH/PUT /petitions/1.json
  def update
    respond_to do |format|
      if @petition.update(petition_params)
        format.html { redirect_to @petition, notice: 'Petition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petitions/1
  # DELETE /petitions/1.json
  def destroy
    @petition.destroy
    respond_to do |format|
      format.html { redirect_to petitions_url }
      format.json { head :no_content }
    end
  end

  def correct_user
    @petition = current_user.petitions.find_by(id: params[:id])
    redirect_to petitions_path, notice: "You don't have permission to edit this petition." if @petition.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petition
      @petition = Petition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def petition_params
      params.require(:petition).permit(:cover, :title, :description, :signum, :target)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def markdown(text)
  options = {
    :autolink => true,
    :space_after_headers => true,
    :no_intra_emphasis => true
  }
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
  markdown.render(text).html_safe
end

def avatar_for(user, options = { size:50})
	avatar_id = Digest::MD5::hexdigest(user.email.downcase)
	"https://seccdn.libravatar.org/avatar/#{avatar_id}.png"
end

end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<small>
		<%= link_to "Activize", "https://github.com/DeadSuperHero/Activize" %> is a project by
		by <%= link_to "DeadSuperHero", "https://github.com/DeadSuperHero" %>
	</small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <a class="navbar-brand" href="/">Activize</a>

	<form class="navbar-form navbar-left" role="search">
	  <div class="form-group">
	    <input type="text" class="form-control" placeholder="Search">
	  </div>
	  <button type="submit" class="btn btn-default">Submit</button>
	</form>

<div id="user-menu">
	<div class="dropdown navbar-right">
  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
	<% if user_signed_in? %>    
    	<div class="user-avatar"><%= image_tag avatar_for current_user %></div>
    	
	    	<div class="user-name">
    	<% unless current_user.name.nil? %>
	    	<strong><%= current_user.name %></strong>
	    <% else %>
	    	<strong><%= current_user.email %></strong>
	    <% end %>
	    </div>

    <% else %>
    <strong>Anonymous User</strong>
    <% end %>
    <span class="caret"></span>
  </button>
		<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
			<% if user_signed_in? %>
		        <li><%= link_to "Create Petition+", new_petition_path %></li>
				<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
				<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li><%= link_to "Login", new_user_session_path %></li>
			<% end %>
		</ul>
	</div>
</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Activize</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<%= render 'layouts/header' %>

<body>

<%= yield %>

</body>
<%= render 'layouts/footer' %>
</html>

app/views/petitions/_form.html.erb
<%= simple_form_for(@petition) do |f| %>
  <% if @petition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@petition.errors.count, "error") %> prohibited this petition from being saved:</h2>

      <ul>
      <% @petition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :cover, label: "Cover Image" %>
  </div>
  <div class="field">
    <%= f.input :title, label: "Title" %>
  </div>
  <div class="field">
    <%= f.input :description %>
  </div>
  <div class="field">
    <%= f.input :signum, label: "Minimum amount of signatures?" %>
  </div>
  <div class="field">
    <%= f.input :target, label: "Who is this petition for?" %>
  </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/petitions/edit.html.erb
<div id="petition-container", class="col-xs-8">
  <div id="petition">
		<h1>Editing petition</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @petition %> |
		<%= link_to 'Back', petitions_path %>
  </div>
</div>

app/views/petitions/index.html.erb
<div id="pagename", class="col-xs-8"><h3>Listing petitions</h3></div>
 <div id="petition-container", class="col-xs-8">
  <div id="petition">
    <% @petitions.each do |petition| %>
        <%= petition.cover %>
        <h2><%= link_to petition.title, petition %></h2>
        <div class="date"><%= petition.created_at %></div>
          <div class="author">
          <%= image_tag avatar_for(petition.user) if petition.user %>
          <%= petition.user.name if petition.user %>
        </div>
        <div class="target"><b>Petition to:</b> <%= petition.target %></div>
        <div class="signum"><b>Number of Signatures Needed: </b><%= petition.signum %></div>
        <%= markdown(petition.description) %>
        <%= link_to 'Show', petition %>
        <% if petition.user == current_user %>
          <%= link_to 'Edit', edit_petition_path(petition) %>
          <%= link_to 'Destroy', petition, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/petitions/new.html.erb
<div id="petition-container", class="col-xs-8">
  <div id="petition">
		<h1>New Petition</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @petition %> |
		<%= link_to 'Back', petitions_path %>
  </div>
</div>

app/views/petitions/show.html.erb
<p id="notice"><%= notice %></p>


<div id="petition-container", class="col-xs-8">
  <div id="petition">

<% if @petition.user == current_user %>
    <%= link_to 'Edit', edit_petition_path(@petition) %>
    <%= link_to "Delete", @petition, method: :delete, data: { confirm: 'Are you sure?'} %>
<% end %>


      <%= @petition.cover %>
      <h2><%= @petition.title %></h2>


      <div class="date">
        <%= @petition.created_at %>
      </div>

      <div class="author">
        <%= image_tag avatar_for(@petition.user) if @petition.user %>
        <%= @petition.user.name if @petition.user %>
      </div>

      <div class="target">
       <b>Petition to:</b> <%= @petition.target %>
      </div>

      <div class="signum">
        <b>Signatures needed:</b> <%= @petition.signum %>
      </div>

      <div class="description">
      <%= markdown(@petition.description) %>
      </div>
    </div>
</div>